// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xyrtubsthitbmlklumxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5cnR1YnN0aGl0Ym1sa2x1bXh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMzMxMzAsImV4cCI6MjA2MTcwOTEzMH0.pkwFH69iXG73tuoH9WW9fnPteP7vdHB2LRI0Yb21jrw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);